export const PRODUCTS_LOADING = 'PRODUCTS_LOADING';
export const PRODUCTS_FAILED = 'PRODUCTS_FAILED';
export const ADD_PRODUCTS = 'ADD_PRODUCTS';

export const ITEMS_LOADING = 'ITEMS_LOADING';
export const ITEMS_FAILED = 'ITEMS_FAILED';
export const ADD_ITEMS = 'ADD_ITEMS';

export const PRODUCT_DATA_UPLOAD_IN_PROGRESS = 'PRODUCT_DATA_UPLOAD_IN_PROGRESS';
export const PRODUCT_DATA_UPLOAD_SUCCESS = 'PRODUCT_DATA_UPLOAD_SUCCESS';
export const PRODUCT_DATA_UPLOAD_FAILED = 'PRODUCT_DATA_UPLOAD_FAILED';

export const INVENTORY_DATA_UPLOAD_IN_PROGRESS = 'INVENTORY_DATA_UPLOAD_IN_PROGRESS';
export const INVENTORY_DATA_UPLOAD_SUCCESS = 'INVENTORY_DATA_UPLOAD_SUCCESS';
export const INVENTORY_DATA_UPLOAD_FAILED = 'INVENTORY_DATA_UPLOAD_FAILED';
